### ISSUE TITLE
New rule

### ISSUE THREAD

**Issue by bajki** [mallardduck/extended-validator-laravel#3]
Hi, how would you create new rule like ProhibitedValueIf

If field 'is_active' is false then that field cannot be some string.

Like   
'email' => ['required', 'email:filter', 'email:dns', 'prohibited_value_if:is_active,0,test@domain.com'],

So if is not active email cannot be test@domain.com.

Thanks

**Comment by mallardduck** [comment]
Solved in #4

**Comment by bajki** [comment]
I have situation where i send emails to user, and that user can be paid or not paid.
If user is paid it can have his email.
If not paid i put 'test@domain.com'.
And on editing i want to disallow to put  'test@domain.com' on paid user.

Message would be : You can't save paid user with email value 'test@domain.com'.

**Comment by mallardduck** [comment]
The new rules have been created and are documented in the readme file.

The the value being referenced is truthy, then you can use `NotInIf`. But if the other field value isn't truthy, you can compare it to a given value with `NotInIfValue`.

In you case the rule applied should be:

```
'email' => ['required', 'email:filter', 'email:dns', 'not_in_if:is_paid,test@domain.com'],
```

This will create a rule where when the value of `is_paid` equals `true`, then the form will not accept `test@domain.com` as the input value.
